### ISSUE TITLE
Api integration

### ISSUE THREAD

**Issue by rarbg** [romanvm/kodi.rarbg#2]
Hey :)
http://torrentapi.org/apidocs.txt
Please use the following api
Keep in mind that v2 is on the way. 90% compatible with the current docs link i just provided you with :)
Also take a look at the project you were added to

**Comment by romanvm** [comment]
Many thanks for the info! I will certainly look into this. Anyway, this is my private pet project and I was not going to announce it publicly.
BTW, is there any way to get IMDB IDs (ttXXXXX) via the API along with other torrent info? I'm going to add some TheTVDB integration for tvshows info and artwork and that would simplify getting the necessary info.

**Comment by rarbg** [comment]
@romanvm 
You can use pubapi_v2.php instead of pubapi.php , with format=json_extended , it should be in stable in 3-4 days. It will give you episode info which has everything you need :)

**Comment by romanvm** [comment]
Thanks!
